name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/DEP@v2
     - run: set -eu
     - run: mkdir "$HOME/.ssh"
     - run: echo "$" > "$HOME/.ssh/DEP"
     - run: chmod 600 "$HOME/.ssh/DEP"
     - run: rsync -e "ssh -p 8822 -i $HOME/.ssh/DEP -o StrictHostKeyChecking=no" --archive --compress --delete . orangepi@openaibot.ru:/home/orangepi/django_projects/deploy-test
