name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Deploy
      - run: rsync -e "ssh -p 4322 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . orangepi@openaibot.ru:/home/orangepi/django_projects/deploy-test
